package com.opencode.remote.ui.strings

import androidx.compose.runtime.*

// ─── Language state ────────────────────────────────────────────────

object AppLocale {
    var language by mutableStateOf("en")
    var darkMode by mutableStateOf(false)
    val strings: AppStrings get() = if (language == "zh") zhStrings else enStrings
}

// ─── Strings container ─────────────────────────────────────────────

data class AppStrings(
    // Connection screen
    val appTitle: String,
    val connectSubtitle: String,
    val hostLabel: String,
    val hostPlaceholder: String,
    val portLabel: String,
    val portPlaceholder: String,
    val usernameLabel: String,
    val usernamePlaceholder: String,
    val passwordLabel: String,
    val passwordPlaceholder: String,
    val useTlsLabel: String,
    val insecureTrustLabel: String,
    val connectButton: String,
    val connecting: String,
    val tipsTitle: String,
    val tipsContent: String,
    val helpLabel: String,

    // Sessions screen
    val sessionList: String,
    val projects: String,
    val sessions: String,
    val serverPath: String,
    val noProjects: String,
    val newSession: String,
    val noSessions: String,
    val noSessionsHint: String,
    val disconnect: String,
    val forkSession: String,
    val delete: String,
    val moreActions: String,
    val close: String,
    val hideChildSessions: String,
    val showChildSessions: String,

    // Chat screen
    val sendFirstMsg: String,
    val inputPlaceholder: String,
    val thinking: String,
    val thinkingActive: String,
    val thought: String,
    val thoughtForSeconds: String,
    val sessionFallback: String,
    val stop: String,
    val refresh: String,
    val todoTitle: String,
    val noTodos: String,
    val toolCalls: String,
    val defaultAgent: String,
    val selectAgent: String,
    val me: String,
    val expand: String,
    val collapse: String,

    // Help screen
    val helpTitle: String,
    val helpBack: String,
    val helpWhatIs: String,
    val helpWhatIsBody: String,
    val helpStep1: String,
    val helpStep1Body: String,
    val helpStep1Code: String,
    val helpStep1After: String,
    val helpStep2: String,
    val helpStep2Bullet1: String,
    val helpStep2Bullet2: String,
    val helpStep2Bullet3: String,
    val helpStep2Bullet4: String,
    val helpStep2HowToIp: String,
    val helpStep2Win: String,
    val helpStep2Mac: String,
    val helpStep2After: String,
    val helpStep3: String,
    val helpStep3Body: String,
    val helpStep3Bullet1: String,
    val helpStep3Bullet2: String,
    val helpStep3Bullet3: String,
    val helpStep3Bullet4: String,
    val helpStep4: String,
    val helpStep4Bullet1: String,
    val helpStep4Bullet2: String,
    val helpStep4Bullet3: String,
    val helpStep4Bullet4: String,
    val helpStep4Bullet5: String,
    val helpAgentTitle: String,
    val helpAgentBody: String,
    val helpAgentBullet1: String,
    val helpAgentBullet2: String,
    val helpAgentBullet3: String,
    val helpTodoTitle: String,
    val helpTodoBody: String,
    val helpFaqTitle: String,
    val helpFaq1Q: String,
    val helpFaq1A: String,
    val helpFaq2Q: String,
    val helpFaq2A: String,
    val helpFaq3Q: String,
    val helpFaq3A: String,
    val helpFaq4Q: String,
    val helpFaq4A: String,
    val helpFaq5Q: String,
    val helpFaq5A: String,
    val helpSecurityTitle: String,
    val helpSecBullet1: String,
    val helpSecBullet2: String,
    val helpSecBullet3: String,
    val helpSecBullet4: String,
    val helpVersion: String,

    // Help - Update check
    val helpUpdateTitle: String,
    val helpUpdateBody: String,
    val helpUpdateBullet1: String,
    val helpUpdateBullet2: String,
    val helpUpdateBullet3: String,
    val helpUpdateBullet4: String,

    // Error messages
    val errEnterIp: String,
    val errInvalidPort: String,
    val errCannotConnect: String,
    val errConnectionFailed: String,
    val errLoadSessions: String,
    val errCreateSession: String,
    val errDeleteSession: String,
    val errForkSession: String,
    val errLoadMessages: String,
    val errStreamInterrupted: String,
    val errUnknown: String,
    val errSendFailed: String,
    val errAbortFailed: String,

    // Update dialog
    val updateAvailable: String,
    val updateDownload: String,
    val updateClose: String,
    val updateChangelog: String,
    val updateChecking: String,
    val updateUpToDate: String,
    val updateGithubFailed: String,

    // Notification
    val notificationRunning: String,
    val notificationChannelName: String,
    val notificationChannelDesc: String,

    // Todo completion
    val todoCompleted: String,
    val todoCompletedDesc: String,
)

// ─── English ───────────────────────────────────────────────────────

val enStrings = AppStrings(
    // Connection
    appTitle = "OConnector",
    connectSubtitle = "Connect to the OpenCode server on your PC",
    hostLabel = "Server Address",
    hostPlaceholder = "e.g. 192.168.1.100",
    portLabel = "Port",
    portPlaceholder = "Default: 4096",
    usernameLabel = "Username",
    usernamePlaceholder = "Optional (default: opencode)",
    passwordLabel = "Password",
    passwordPlaceholder = "Optional",
    useTlsLabel = "Use HTTPS (TLS)",
    insecureTrustLabel = "Allow untrusted certificates",
    connectButton = "Connect",
    connecting = "Connecting...",
    tipsTitle = "Quick Tips",
    tipsContent = "1. Run on PC: opencode serve --hostname=0.0.0.0 --port=4096\n2. Ensure phone and PC are on the same network\n3. Check PC firewall allows the port",
    helpLabel = "Help",

    // Sessions
    sessionList = "Sessions",
    projects = "Projects",
    sessions = "sessions",
    serverPath = "Server Path",
    noProjects = "No Projects",
    newSession = "New Session",
    noSessions = "No Sessions",
    noSessionsHint = "Tap the button below to create one",
    disconnect = "Disconnect",
    forkSession = "Fork Session",
    delete = "Delete",
    moreActions = "More",
    close = "Close",
    hideChildSessions = "Hide child sessions",
    showChildSessions = "Show child sessions",

    // Chat
    sendFirstMsg = "Send a message to start",
    inputPlaceholder = "Type a message...",
    thinking = "thinking...",
    thinkingActive = "💭 Thinking...",
    thought = "💭 Thought",
    thoughtForSeconds = "💭 Thought for %ds",
    sessionFallback = "Session",
    stop = "Stop",
    refresh = "Refresh",
    todoTitle = "Todo List",
    noTodos = "No tasks yet",
    toolCalls = "tool calls",
    defaultAgent = "Default",
    selectAgent = "Select Agent",
    me = "Me",
    expand = "Expand",
    collapse = "Collapse",

    // Help
    helpTitle = "Help",
    helpBack = "Back",
    helpWhatIs = "What is OConnector",
    helpWhatIsBody = "OConnector is an Android remote client that lets you control the OpenCode AI coding assistant running on your PC via your phone or tablet. Your phone and PC must be on the same local network.",
    helpStep1 = "Step 1: Start the PC Server",
    helpStep1Body = "Run the following command in your PC terminal to start the server:",
    helpStep1Code = "opencode serve --hostname=0.0.0.0 --port=4096",
    helpStep1After = "Do not close the terminal after starting. You should see \"Server listening\" to confirm it's running.",
    helpStep2 = "Step 2: Connect from Phone",
    helpStep2Bullet1 = "1. Open the app and go to the connection page",
    helpStep2Bullet2 = "2. Enter your PC's local IP address",
    helpStep2Bullet3 = "3. Keep port as default 4096; fill Username/Password only if server requires auth",
    helpStep2Bullet4 = "4. Tap \"Connect\"",
    helpStep2HowToIp = "How to find your PC's IP address:",
    helpStep2Win = "Windows: Open CMD, run ipconfig, look for \"IPv4 Address\"",
    helpStep2Mac = "macOS / Linux: Run ifconfig or hostname -I in terminal",
    helpStep2After = "You'll be taken to the sessions list after a successful connection.",
    helpStep3 = "Step 3: Projects & Sessions",
    helpStep3Body = "After connecting, you'll see all projects on your PC grouped by working directory.",
    helpStep3Bullet1 = "Tap a project card → view sessions in that project",
    helpStep3Bullet2 = "Tap a session → open chat",
    helpStep3Bullet3 = "Bottom-right \"+\" → create new session (auto-opens chat)",
    helpStep3Bullet4 = "Right-side \"⋮\" menu → Fork or delete",
    helpStep4 = "Step 4: Chat",
    helpStep4Bullet1 = "Type in the input box at the bottom → tap send",
    helpStep4Bullet2 = "AI responses stream in real-time",
    helpStep4Bullet3 = "Thinking process shows in a \uD83D\uDCAD thinking bubble",
    helpStep4Bullet4 = "Tool call count shows in a tool bubble",
    helpStep4Bullet5 = "Tap the \u23F9 stop button in the toolbar to abort generation",
    helpAgentTitle = "Select Agent",
    helpAgentBody = "The chat toolbar has a \uD83E\uDD16 button. Tap it to select a different Agent:",
    helpAgentBullet1 = "\"Default\" = let the server choose the primary agent automatically",
    helpAgentBullet2 = "Select another Agent = use that agent to handle your messages",
    helpAgentBullet3 = "Agent list is loaded from the server automatically",
    helpTodoTitle = "View Todo",
    helpTodoBody = "If the AI is executing tasks, a \uD83D\uDCCB button with a count badge appears in the toolbar. Tap to expand the Todo panel and check task progress.",
    helpFaqTitle = "FAQ",
    helpFaq1Q = "Connection failed?",
    helpFaq1A = "1) Confirm opencode serve is running on PC\n2) Verify the IP address is correct\n3) Check firewall allows port 4096\n4) Ensure phone and PC are on the same WiFi",
    helpFaq2Q = "Session working directory is wrong?",
    helpFaq2A = "New session working directory = the directory where opencode serve was started. cd to the target directory before starting the server.",
    helpFaq3Q = "No response after sending a message?",
    helpFaq3A = "1) Check PC terminal for log output\n2) Try stopping and resending\n3) Confirm OpenCode API Key is configured",
    helpFaq4Q = "Can multiple phones connect simultaneously?",
    helpFaq4A = "Yes, but operating the same session from multiple devices may cause conflicts.",
    helpFaq5Q = "Does the server support authentication?",
    helpFaq5A = "Yes. Set environment variable OPENCODE_SERVER_PASSWORD before starting the server to enable auth (username defaults to \"opencode\", override with OPENCODE_SERVER_USERNAME).\n\nWindows:\nset OPENCODE_SERVER_PASSWORD=your-password\nopencode serve --hostname=0.0.0.0 --port=4096\n\nmacOS / Linux:\nOPENCODE_SERVER_PASSWORD=your-password opencode serve --hostname=0.0.0.0 --port=4096\n\nThen fill in the Username and Password fields in the app.",
    helpSecurityTitle = "Security",
    helpSecBullet1 = "Only use on trusted local networks",
    helpSecBullet2 = "Use Tailscale / ZeroTier for remote access",
    helpSecBullet3 = "Never expose the port to the public internet",
    helpSecBullet4 = "Do not use on public WiFi",
    helpVersion = "OConnector v${com.opencode.remote.BuildConfig.VERSION_NAME}",

    helpUpdateTitle = "Check for Updates",
    helpUpdateBody = "The app automatically checks GitHub for new versions when you open the connection page.",
    helpUpdateBullet1 = "If a new version is available, a download icon (⬇) appears next to the language button",
    helpUpdateBullet2 = "Tap the icon to view the changelog and download the update",
    helpUpdateBullet3 = "The APK will be downloaded to your Downloads folder and installed automatically",
    helpUpdateBullet4 = "If GitHub is unreachable, the update check is silently skipped",

    // Error messages
    errEnterIp = "Please enter server IP address",
    errInvalidPort = "Please enter a valid port (1-65535)",
    errCannotConnect = "Cannot connect to server. Check IP and port.",
    errConnectionFailed = "Connection failed: %s",
    errLoadSessions = "Failed to load sessions: %s",
    errCreateSession = "Failed to create session: %s",
    errDeleteSession = "Delete failed: %s",
    errForkSession = "Fork failed: %s",
    errLoadMessages = "Failed to load messages: %s",
    errStreamInterrupted = "Event stream interrupted: %s",
    errUnknown = "Unknown error",
    errSendFailed = "Send failed: %s",
    errAbortFailed = "Abort failed: %s",

    updateAvailable = "Update Available",
    updateDownload = "Download",
    updateClose = "Close",
    updateChangelog = "Changelog",
    updateChecking = "Checking for updates...",
    updateUpToDate = "Already up to date",
    updateGithubFailed = "GitHub connection failed. Please connect to a suitable network.",
    notificationRunning = "OConnector is running",
    notificationChannelName = "OConnector Service",
    notificationChannelDesc = "Keeps connection to server alive",
    todoCompleted = "Tasks Completed",
    todoCompletedDesc = "%s's task list is completed",
)

// ─── Chinese ───────────────────────────────────────────────────────

val zhStrings = AppStrings(
    // Connection
    appTitle = "OConnector",
    connectSubtitle = "连接到 PC 上的 OpenCode 服务器",
    hostLabel = "服务器地址",
    hostPlaceholder = "例如: 192.168.1.100",
    portLabel = "端口",
    portPlaceholder = "默认: 4096",
    usernameLabel = "用户名",
    usernamePlaceholder = "可选（默认: opencode）",
    passwordLabel = "密码",
    passwordPlaceholder = "可选",
    useTlsLabel = "使用 HTTPS (TLS)",
    insecureTrustLabel = "允许不受信任的证书",
    connectButton = "连接服务器",
    connecting = "连接中...",
    tipsTitle = "\uD83D\uDCA1 使用提示",
    tipsContent = "1. 在 PC 上运行: opencode serve --hostname=0.0.0.0 --port=4096\n2. 确保手机与 PC 在同一局域网\n3. 检查 PC 防火墙是否允许该端口",
    helpLabel = "帮助",

    // Sessions
    sessionList = "会话列表",
    projects = "项目",
    sessions = "个会话",
    serverPath = "服务器路径",
    noProjects = "暂无项目",
    newSession = "新建会话",
    noSessions = "暂无会话",
    noSessionsHint = "点击下方按钮创建第一个会话",
    disconnect = "断开连接",
    forkSession = "Fork 会话",
    delete = "删除",
    moreActions = "更多操作",
    close = "关闭",
    hideChildSessions = "隐藏子会话",
    showChildSessions = "显示子会话",

    // Chat
    sendFirstMsg = "发送第一条消息开始对话",
    inputPlaceholder = "输入消息...",
    thinking = "思考中...",
    thinkingActive = "💭 正在思考...",
    thought = "💭 思考",
    thoughtForSeconds = "💭 思考了 %d 秒",
    sessionFallback = "会话",
    stop = "停止生成",
    refresh = "刷新",
    todoTitle = "Todo 列表",
    noTodos = "暂无待办事项",
    toolCalls = "个工具调用",
    defaultAgent = "默认",
    selectAgent = "选择 Agent",
    me = "我",
    expand = "展开",
    collapse = "收起",

    // Help
    helpTitle = "使用帮助",
    helpBack = "返回",
    helpWhatIs = "OConnector 是什么",
    helpWhatIsBody = "OConnector 是一个 Android 远程控制端，让你通过手机/平板操控 PC 上运行的 OpenCode AI 编程助手。手机和 PC 需要在同一局域网内。",
    helpStep1 = "第一步：启动 PC 服务器",
    helpStep1Body = "在 PC 终端运行以下命令启动服务器：",
    helpStep1Code = "opencode serve --hostname=0.0.0.0 --port=4096",
    helpStep1After = "启动后不要关闭终端窗口。看到 \"Server listening\" 提示表示启动成功。",
    helpStep2 = "第二步：手机连接服务器",
    helpStep2Bullet1 = "1. 打开 app，进入连接页",
    helpStep2Bullet2 = "2. 输入 PC 的局域网 IP 地址",
    helpStep2Bullet3 = "3. 端口保持默认 4096；用户名和密码仅在服务器开启认证时填写",
    helpStep2Bullet4 = "4. 点击「连接」",
    helpStep2HowToIp = "如何查看 PC 的 IP 地址：",
    helpStep2Win = "Windows：打开 CMD，运行 ipconfig，找到「IPv4 地址」",
    helpStep2Mac = "macOS / Linux：终端运行 ifconfig 或 hostname -I",
    helpStep2After = "连接成功后自动跳转到会话列表页。",
    helpStep3 = "第三步：项目与会话",
    helpStep3Body = "连接后显示 PC 上所有项目（按工作目录分组），点进项目查看该目录下的会话。",
    helpStep3Bullet1 = "点击项目卡片 → 查看该项目下的会话",
    helpStep3Bullet2 = "点击会话 → 进入聊天",
    helpStep3Bullet3 = "右下角「＋」→ 新建会话（自动进入聊天页面）",
    helpStep3Bullet4 = "右侧「⋮」菜单 → Fork 或删除",
    helpStep4 = "第四步：聊天",
    helpStep4Bullet1 = "底部输入框输入文字 → 点击发送",
    helpStep4Bullet2 = "AI 回复会实时流式显示",
    helpStep4Bullet3 = "思考过程显示在 \uD83D\uDCAD 思考 气泡中",
    helpStep4Bullet4 = "工具调用数量显示在工具气泡中",
    helpStep4Bullet5 = "生成中可点击顶栏 \u23F9 停止按钮中止",
    helpAgentTitle = "选择 Agent",
    helpAgentBody = "聊天页面顶栏有一个 \uD83E\uDD16 按钮，点击可以选择不同的 Agent：",
    helpAgentBullet1 = "「默认」= 让服务器自动选择主 agent",
    helpAgentBullet2 = "选择其他 Agent = 用指定 agent 处理你的消息",
    helpAgentBullet3 = "Agent 列表从服务器自动加载，不同配置可能显示不同 agent",
    helpTodoTitle = "查看 Todo",
    helpTodoBody = "如果 AI 在执行任务，顶栏会显示 \uD83D\uDCCB 按钮（带数字徽标）。点击可展开 Todo 面板查看任务进度。",
    helpFaqTitle = "常见问题",
    helpFaq1Q = "连接失败怎么办？",
    helpFaq1A = "① 确认 PC 上 opencode serve 已运行\n② 确认 IP 地址正确\n③ 检查防火墙是否放行了端口 4096\n④ 确认手机和 PC 在同一 WiFi 下",
    helpFaq2Q = "创建的会话工作目录不对？",
    helpFaq2A = "新会话的工作目录 = PC 上运行 opencode serve 时所在的目录。需要先 cd 到目标目录再启动服务器。",
    helpFaq3Q = "发消息后没反应？",
    helpFaq3A = "① 检查 PC 终端是否有日志输出\n② 尝试点停止后重发\n③ 确认 OpenCode 的 API Key 已配置",
    helpFaq4Q = "可以多台手机同时连接吗？",
    helpFaq4A = "可以，但多台手机操作同一个会话可能产生冲突。",
    helpFaq5Q = "服务器支持认证吗？",
    helpFaq5A = "支持。启动服务器前设置环境变量 OPENCODE_SERVER_PASSWORD 即可启用认证（用户名默认为 \"opencode\"，可通过 OPENCODE_SERVER_USERNAME 修改）。\n\nWindows:\nset OPENCODE_SERVER_PASSWORD=你的密码\nopencode serve --hostname=0.0.0.0 --port=4096\n\nmacOS / Linux:\nOPENCODE_SERVER_PASSWORD=你的密码 opencode serve --hostname=0.0.0.0 --port=4096\n\n启用后在 app 的用户名和密码字段中填写即可。",
    helpSecurityTitle = "安全提示",
    helpSecBullet1 = "仅在可信局域网内使用",
    helpSecBullet2 = "远程访问请使用 Tailscale / ZeroTier 加密通道",
    helpSecBullet3 = "不要将端口暴露到公网",
    helpSecBullet4 = "不要在公共 WiFi 下使用",
    helpVersion = "OConnector v${com.opencode.remote.BuildConfig.VERSION_NAME}",

    helpUpdateTitle = "检查更新",
    helpUpdateBody = "打开连接页面时，应用会自动检查 GitHub 上是否有新版本。",
    helpUpdateBullet1 = "如果有新版本，语言按钮旁边会出现下载图标 (⬇)",
    helpUpdateBullet2 = "点击图标可查看更新日志并下载更新",
    helpUpdateBullet3 = "APK 会下载到手机的 Downloads 文件夹并自动弹出安装",
    helpUpdateBullet4 = "如果无法连接 GitHub，更新检查会被静默跳过",

    // Error messages
    errEnterIp = "请输入服务器 IP 地址",
    errInvalidPort = "请输入有效端口号 (1-65535)",
    errCannotConnect = "无法连接到服务器，请检查 IP 和端口是否正确",
    errConnectionFailed = "连接失败: %s",
    errLoadSessions = "加载会话失败: %s",
    errCreateSession = "创建会话失败: %s",
    errDeleteSession = "删除失败: %s",
    errForkSession = "Fork 失败: %s",
    errLoadMessages = "加载消息失败: %s",
    errStreamInterrupted = "事件流中断: %s",
    errUnknown = "未知错误",
    errSendFailed = "发送失败: %s",
    errAbortFailed = "中断失败: %s",

    updateAvailable = "发现新版本",
    updateDownload = "下载",
    updateClose = "关闭",
    updateChangelog = "更新日志",
    updateChecking = "正在检查更新...",
    updateUpToDate = "已是最新版本",
    updateGithubFailed = "GitHub 连接失败，请接入合适的网络环境",
    notificationRunning = "OConnector 正在运行",
    notificationChannelName = "OConnector 服务",
    notificationChannelDesc = "保持与服务器的连接",
    todoCompleted = "任务完成",
    todoCompletedDesc = "%s的任务列表已完成",
)
